global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mistral-inference-server'
    static_configs:
      - targets: ['vllm-server:8000']
    metrics_path: /metrics
