receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  resource:
    attributes:
      - key: service.name
        value: "mistral-inference-server"
        action: upsert

exporters:
  otlp:
    endpoint: "ingest.signoz.cloud:443"  # SigNoz Cloud endpoint
    tls:
      insecure: false
    headers:
      "signoz-access-token": "${SIGNOZ_ACCESS_TOKEN}"  # Your SigNoz Cloud access token

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp]
